[package]
name = "hurdat2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3"
geo = "0.20.1"
kml = "0.4.3"
rayon = "1.5.3"
